name: Release

on:
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn prettier . -c
      - run: yarn eslint src

  semantic-release:
    runs-on: ubuntu-latest
    needs: [quality-checks]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_AUTHOR_NAME: 'Johnny Estilles'
          GIT_AUTHOR_EMAIL: 'johnny@estilles.com'
          GIT_COMMITTER_NAME: 'Johnny Estilles'
          GIT_COMMITTER_EMAIL: 'johnny@estilles.com'
